Feat/report charts
Multiwoven/multiwoven-ui pull request #96
Opened 2024-03-05 12:20 UTC by macintushar

## Description
Added the charts to display the number of Sync Runs, Rows Processed and Rows Failed in the Dashboard. There is also filtering based on the time that we are reporting (1 day and 1 week).
[Screen_recording_20230829_092300.webm](https://github.com/Multiwoven/multiwoven-ui/assets/54372016/4fc3da89-f960-4434-8f87-ddaf85fd31a8)

## Related Issue
None

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would impact existing functionality)
- [ ] Styling change
- [ ] Documentation update
- [ ] Refactoring
- [ ] Chore
  
## How Has This Been Tested?

## Checklist:
- [x] Ensure a branch name is prefixed with `feature`, `bugfix`, `hotfix`, `release`, `style` or `chore` followed by `/` and branch name e.g `feature/add-salesforce-connector`
- [ ] Added unit tests for the changes made (if required)
- [x] Have you made sure the commit messages meets the guidelines?
- [x] Added relevant screenshots for the changes
- [x] Have you tested the changes on local/staging?
- [x] Have you made sure the code you have written follows the best practises to the best of your knowledge?

2024-03-05 14:48 UTC, sumitd94 commented on src/components/Badge/Badge.tsx
> +    textColor: 'black.300',
why is this changed?

2024-03-05 14:48 UTC, sumitd94 commented on src/routes/index.tsx
> +    component: <SuspenseWithLoader redirectRoute='/'>{<Dashboard />}</SuspenseWithLoader>,
let's comment this back since the entire feature is not in place

2024-03-05 14:50 UTC, sumitd94 commented on src/views/Dashboard/Dashboard.tsx
> +            </Stack>
We can move this entire logic into the separate `chart` component and call the component here.
Want to keep the dashboard file clean and simple.

2024-03-05 14:51 UTC, sumitd94 commented on src/views/Dashboard/Reports/ChartCard.tsx
> +};
can we please move these into separate `types` file and define all the types over there for dashboard?

2024-03-05 14:52 UTC, sumitd94 commented on src/views/Dashboard/Reports/ChartCard.tsx
> +  };
NIT: we can move this outside of the component and declare it on top

2024-03-05 14:53 UTC, sumitd94 commented on src/views/Dashboard/Reports/ChartCard.tsx
> +        <></>
NIT: `null` maybe

2024-03-05 14:56 UTC, sumitd94 commented on src/views/Dashboard/Reports/SyncRunsErrors/SyncRunsErrors.tsx
> +};
almost the similar set of logic in rows failed, rows processed.
Can we generalize the component and pass the data as props?

2024-03-05 14:56 UTC, sumitd94 requested changes
Added few comments, looks good otherwise.

2024-03-05 15:05 UTC, macintushar commented on src/components/Badge/Badge.tsx
> +    textColor: 'black.300',
It wasn't as per figma

2024-03-05 15:08 UTC, macintushar commented on src/views/Dashboard/Dashboard.tsx
> +            </Stack>
I kept it this way since I wanted the API Call to be in the Dashboard file. We need to also think about how it will affect when we do connector-based filtering. I kept the `Reports` component for that reason. It makes it easy to pass data to it.

2024-03-06 16:37 UTC, macintushar commented on src/views/Dashboard/Reports/Reports.tsx
> +  return (
Will look into this later but we're using return consistently across most parts of the repo

2024-03-06 16:37 UTC, macintushar commented on src/views/Dashboard/Reports/ChartCard.tsx
> +        <></>
Done

2024-03-06 16:39 UTC, macintushar commented on src/views/Dashboard/Reports/ChartCard.tsx
> +  };
Done

2024-03-06 16:39 UTC, macintushar commented on src/views/Dashboard/Reports/ChartCard.tsx
> +};
Done

2024-03-06 16:39 UTC, macintushar commented on src/routes/index.tsx
> +    component: <SuspenseWithLoader redirectRoute='/'>{<Dashboard />}</SuspenseWithLoader>,
Done

2024-03-06 17:58 UTC, sumitd94 approved these changes

2024-03-06 17:58 UTC, merged