feat: paginate connectors list
Multiwoven/multiwoven-ui pull request #97
Opened 2024-03-05 17:03 UTC by sumitd94

## Description
Added pagination to the list of connectors we are showing

<img width="371" alt="Screenshot 2024-03-05 at 10 33 35 PM" src="https://github.com/Multiwoven/multiwoven-ui/assets/29303618/096fe566-c8c8-4568-9e67-2b6928d4fdec">

## Related Issue

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would impact existing functionality)
- [ ] Styling change
- [ ] Documentation update
- [ ] Refactoring
- [ ] Chore
  
## How Has This Been Tested?

## Checklist:
- [ ] Ensure a branch name is prefixed with `feature`, `bugfix`, `hotfix`, `release`, `style` or `chore` followed by `/` and branch name e.g `feature/add-salesforce-connector`
- [ ] Added unit tests for the changes made (if required)
- [ ] Have you made sure the commit messages meets the guidelines?
- [ ] Added relevant screenshots for the changes
- [ ] Have you tested the changes on local/staging?
- [ ] Have you made sure the code you have written follows the best practises to the best of your knowledge?

2024-03-05 18:07 UTC, macintushar requested changes

2024-03-05 18:07 UTC, macintushar commented on src/views/Dashboard/ListConnectors.tsx
>  import { ConnectorItem } from '../Connectors/types';
Imports should be using `@` and not be absolute like `../../`

2024-03-05 18:07 UTC, macintushar commented on src/views/Dashboard/Pagination.tsx
NIT :  file can be in its own directory like `/Dashboard/Pagination/Pagination.tsx `

2024-03-05 18:07 UTC, macintushar commented on src/views/Dashboard/Pagination.tsx
> +      <MdKeyboardArrowLeft color='#98A2B3' />
Are the color's used in this not already available in our custom color tokens? If not then they should be updated in the design to use our existing color tokens, unless it's a new color

2024-03-06 17:56 UTC, sumitd94 commented on src/views/Dashboard/Pagination.tsx
> +      <MdKeyboardArrowLeft color='#98A2B3' />
the icons do not support tokens unfortunately!

2024-03-06 17:57 UTC, sumitd94 commented on src/views/Dashboard/ListConnectors.tsx
>  import { ConnectorItem } from '../Connectors/types';
Will push this in a different PR, not part of this PR change :P

2024-03-06 17:57 UTC, merged